PixelLauncher: Use RELAX_USES_LIBRARY_CHECK
FAILED: Verifying uses-libraries: vendor/PixelLauncher/Prebuilts/system_ext/priv-app/WallpaperPickerGoogleRelease/WallpaperPickerGoogleRelease.apk
Outputs: out/target/common/obj/APPS/WallpaperPickerGoogleReleaseMod_intermediates/enforce_uses_libraries.status
Error: exited with code: 1
Command: /bin/bash -c "(rm -f out/target/common/obj/APPS/WallpaperPickerGoogleReleaseMod_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py         --enforce-uses-libraries        --enforce-uses-libraries-status out/target/common/obj/APPS/WallpaperPickerGoogleReleaseMod_intermediates/enforce_uses_libraries.status         --aapt out/host/linux-x86/bin/aapt                                     vendor/PixelLauncher/Prebuilts/system_ext/priv-app/WallpaperPickerGoogleRelease/WallpaperPickerGoogleRelease.apk )"
Output:
error: mismatch in the <uses-library> tags between the build system and the manifest:
        - required libraries in build system: []
                         vs. in the manifest: []
        - optional libraries in build system: []
                         vs. in the manifest: [org.apache.http.legacy]
        - tags in the manifest (vendor/PixelLauncher/Prebuilts/system_ext/priv-app/WallpaperPickerGoogleRelease/WallpaperPickerGoogleRelease.apk):
                uses-library-not-required:'org.apache.http.legacy'
note: the following options are available:
        - to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
        - to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
        - to fix the check, make build system properties coherent with the manifest
        - see build/make/Changes.md for details

Signed-off-by: OdSazib <odsazib@gmail.com>